name: Build and Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'huangjj27'
  workflow_run:
    workflows:
      - Check
    type:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
