name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'huangjj27'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  pull_request:
    branches:
      - dev
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    needs:
      - format
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  release-cratesio:
    if: github.event_name == 'workflow_dispatch'
