name: CI

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches:
      - dev
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  publish:
    needs: build_test
    strategy:
      fail-fast: false
      matrix:
        crate: ["idcard"]
    # if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ${{ matrix.crate }} & pwd
      - name: login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: $CRATESIO_TOKEN
      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
