name: Continuous Integration

on:
  pull_request:
    branches:
      - dev
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  check:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    if: github.event_name != 'workflow_dispatch'
    needs:
      - format
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    if: github.event_name != 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
